config/routes.rb
Store::Application.routes.draw do
  
  resources :categories, :products

  root to: "products#index"

end

  #   end

app/models/association.rb
class Association < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :associations
	has_many :products, through: :associations
end

app/models/example.rb
class Example < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :associations
	has_many :categories, through: :associations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end

	def show
		id = params.require(:id)
		@category = Category.find(id)
		@products = @category.products
	end

	def new
		@category = Category.new
	end

	def create
		category = Category.create(name: params["category"]["name"])
		redirect_to category
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		category = Category.find(params[:id])
		updated_info = params.require(:category).permit(:name)
		category.update_attributes(updated_info)
		redirect_to category
	end

	def destroy
		id = params.require(:id)
		category = Category.find(id)
		category.destroy
		redirect_to "/categories"
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all
	end
	
	def show
		id = params.require(:id)
		@product = Product.find(id)
		@categories = @product.categories
	end

	def new
		@product = Product.new
	end

	def create
		if params["product"]["name"] == "" || params["product"]["price"] == ""
			flash.now[:warning] = "Please Fill Out Entire Form"
			redirect_to new_product_path
		else
			product = Product.create(name: params["product"]["name"], price: params["product"]["price"])
			params["product"]["category_ids"].each { |x| product.categories.push(Category.find(x)) if x != "" }
			redirect_to product
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		product = Product.find(params[:id])
		updated_info = params.require(:product).permit(:name, :price)
		if params["product"]["name"] == "" || params["product"]["price"] == ""
			flash[:warning] = "Name/Price CANNOT be empty!"
			redirect_to edit_product_path
		else
			product.update_attributes(updated_info)
			product.category_ids = params["product"]["category_ids"]
			redirect_to product
		end
	end

	def destroy
		product = Product.find(params[:id])
		product.destroy
		redirect_to products_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

	<%= f.text_field :name, placeholder: "Category Name" %><br>

<%= f.submit class: "btn btn-large"%>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category: <%= @category.name %></h1>

<%= render "form" %>

<br><br>

<%= link_to "DELETE", category_path, method: :delete %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table class="table table-hover">

	<th class="tablelabel">Category Name</th>
	<th class="tablelabel">Products</th>
	<th class="tablelabel"></th>

	<% @categories.each do |c| %>
		<tr>
			<td class="categoryinfo"> <%= link_to c.name, category_path(c) %> </td>
			<td class="categoryinfo"> <% c.products.each do |x| %> <%= x.name %><br> <% end %> </td>
			<td class="productinfo"> <%= link_to "Edit", edit_category_path(c) %> </td>
		</tr>
	<% end %>

</table>

app/views/categories/new.html.erb
<h1>Add A Category</h1>

<%= render "form" %>

app/views/categories/show.html.erb
<h2>Products in <%= @category.name %></h2>

<ul>
	<% @products.each do |p| %>
		<li>
			<%= p.name %> -> $<%= p.price %>
		</li>
	<% end %>
</ul>

<%= link_to "All Categories", categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<ul class="nav nav-pills">
  <li><%= link_to "Products", products_path %></li>
  <li><%= link_to "Categories", categories_path %></li>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      Create <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Product", new_product_path %></li>
      <li><%= link_to "Category", new_category_path %></li>
    </ul>
  </li>
</ul>
<div class="container">
	<div class="row">
		<%= yield %>
	</div>
</div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>

<%= f.text_field :name, placeholder: "Product Name" %> <br>
<%= f.number_field :price, step: 0.01, placeholder: "Price XX.XX" %> <br>
<%= collection_check_boxes :product, :category_ids, Category.all, :id, :name %> <br>

<%= f.submit class: "btn btn-large" %>

<% end %>

app/views/products/edit.html.erb
<h1>Edit Product: <%= @product.name %></h1>

<%= render "form" %>

<%= link_to "DELETE", product_path, method: :delete%>

app/views/products/index.html.erb
<h1>Products</h1>

<table class="table table-hover">

	<th class="tablelabel">Product Name</th>
	<th class="tablelabel">Price</th>
	<th class="tablelabel">Categories</th>
	<th class="tablelabel"></th>

	<% @products.each do |p| %>
		<tr>
			<td class="productinfo"> <%= link_to p.name, product_path(p) %> </td>
			<td class="productinfo"> $<%= p.price %> </td>
			<td class="productinfo"> <% p.categories.each do |x| %> <%= x.name %><br> <% end %> </td>
			<td class="productinfo"> <%= link_to "Edit", edit_product_path(p) %> </td>
		</tr>
	<% end %>

</table>

app/views/products/new.html.erb
<h1>Add A Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>

<ul>
	<li>Price: $<%=@product.price%></li>
	<li>Categories:<br>
		<% @categories.each do |c| %>
			<%= c.name %><br>
		<% end %>
	</li>
</ul>

<%= link_to "Edit", edit_product_path %><br><br>